version: "3"

services:
  db:
    image: postgres:16.0
    restart: always
    env_file:
      - .env
    ports:
      - "${DB_EXT_PORT}:${DB_INT_PORT}"
    volumes:
      - .db:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  app:
    build: .
    ports:
      - "${API_EXT_PORT}:${API_INT_PORT}"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
