// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/actor/": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Получения списка актеров",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "actor"
                ],
                "summary": "Get actors",
                "operationId": "get-actors",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.GetActors"
                        }
                    },
                    "400": {
                        "description": "error string",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "unauthtorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Создание записи об актере",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "actor"
                ],
                "summary": "Add actor",
                "operationId": "post-actor",
                "parameters": [
                    {
                        "description": "Информация об актере",
                        "name": "requestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ActorPost"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "actor added",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "error string",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "unauthtorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/actor/{id}": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Поиск актера по id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "actor"
                ],
                "summary": "Get actor",
                "operationId": "get-actor",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ActorRespond"
                        }
                    },
                    "400": {
                        "description": "error string",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "unauthtorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Изменение записи об актере",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "actor"
                ],
                "summary": "Update actor",
                "operationId": "put-actor",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Информация об актере",
                        "name": "requestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ActorPost"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "actor updated",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "error string",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "unauthtorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Удаление актера по id",
                "tags": [
                    "actor"
                ],
                "summary": "Delete actor",
                "operationId": "delete-actor",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "actor deleted",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "error string",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "unauthtorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/film/": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Получения списка фильмов",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "film"
                ],
                "summary": "Get films",
                "operationId": "get-films",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.GetFilms"
                        }
                    },
                    "400": {
                        "description": "error string",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "unauthtorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Создание записи об фильме",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "film"
                ],
                "summary": "Add film",
                "operationId": "post-film",
                "parameters": [
                    {
                        "description": "Информация о фильме` + "`" + `",
                        "name": "requestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.FilmPostDoc"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "film added",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "error string",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "unauthtorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/film/{id}": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Поиск фильма по id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "film"
                ],
                "summary": "Get film",
                "operationId": "get-film",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.FilmRespond"
                        }
                    },
                    "400": {
                        "description": "error string",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "unauthtorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Изменение записи о фильме",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "film"
                ],
                "summary": "Update film",
                "operationId": "put-film",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Информация о фильме",
                        "name": "requestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.FilmPostDoc"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "film updated",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "error string",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "unauthtorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Удаление фильма по id",
                "tags": [
                    "film"
                ],
                "summary": "Delete film",
                "operationId": "delete-film",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "film deleted",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "error string",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "unauthtorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/search/": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Поиск фильмов по фрагменту из названия или фрагменту имени актера, который указан в титрах",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "search"
                ],
                "summary": "Search",
                "operationId": "search",
                "parameters": [
                    {
                        "type": "string",
                        "description": "искомый фрагмент",
                        "name": "search_by",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.FilmsSearch"
                        }
                    },
                    "400": {
                        "description": "error string",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "unauthtorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/sign-up/": {
            "post": {
                "description": "Регистрация пользователя",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Sign up",
                "operationId": "sing-up",
                "parameters": [
                    {
                        "description": "Пароль + юзернейм",
                        "name": "requestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SignUpRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "user signed up",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "error string",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Actor": {
            "type": "object",
            "properties": {
                "birthdate": {
                    "$ref": "#/definitions/models.CustomDate"
                },
                "first_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "last_name": {
                    "type": "string"
                },
                "sex": {
                    "type": "string"
                }
            }
        },
        "models.ActorPost": {
            "type": "object",
            "properties": {
                "birthdate": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "sex": {
                    "type": "string"
                }
            }
        },
        "models.ActorRespond": {
            "type": "object",
            "properties": {
                "actor": {
                    "$ref": "#/definitions/models.Actor"
                },
                "films": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Film"
                    }
                }
            }
        },
        "models.CustomDate": {
            "type": "object",
            "properties": {
                "time.Time": {
                    "type": "string"
                }
            }
        },
        "models.Film": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "rating": {
                    "type": "integer"
                },
                "release_date": {
                    "$ref": "#/definitions/models.CustomDate"
                }
            }
        },
        "models.FilmDoc": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "rating": {
                    "type": "integer"
                },
                "release_date": {
                    "type": "string"
                }
            }
        },
        "models.FilmPostDoc": {
            "type": "object",
            "properties": {
                "actors_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "film": {
                    "$ref": "#/definitions/models.FilmDoc"
                }
            }
        },
        "models.FilmRespond": {
            "type": "object",
            "properties": {
                "actors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Actor"
                    }
                },
                "film": {
                    "$ref": "#/definitions/models.Film"
                }
            }
        },
        "models.FilmsSearch": {
            "type": "object",
            "properties": {
                "films": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Film"
                    }
                }
            }
        },
        "models.GetActors": {
            "type": "object",
            "properties": {
                "actors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ActorRespond"
                    }
                }
            }
        },
        "models.GetFilms": {
            "type": "object",
            "properties": {
                "actors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.FilmRespond"
                    }
                }
            }
        },
        "models.SignUpRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8888",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "VK backend trainee task API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
